# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web development blog
email: hello@fhergomez.com
description: > # this means to ignore newlines until "baseurl:"
  Daily blog from Fernando Gomez
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:8080" # the base hostname & protocol for your site
twitter_username: fhergomez70
github_username:  fhergomez

# Build settings
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /articles/:title
